### ISSUE TITLE
Bad VPK Version (4294967041)

### ISSUE THREAD

**Issue by CENTURYWIND** [SteamDatabase/ValvePak#11]
### Describe the bug

Whether I open the VPK using GCFScape or VRF, you will be prompted with the VPK version problem.
VRF displays "Bad VPK version. (4294967041)". 
This is an L4D2 game package file. The game can read it, but the unpacking softwares cannot read the file

### What Valve game does this happen in

Left 4 Dead 2

### Reference file in a Source 2 game

（Not an official vpk file）

### Expected behavior

System.IO.InvalidDataException: Bad VPK version. (4294967041)
   at SteamDatabase.ValvePak.Package.Read(Stream input) in /home/runner/work/ValvePak/ValvePak/ValvePak/ValvePak/Package.cs:line 203
   at SteamDatabase.ValvePak.Package.Read(String filename) in /home/runner/work/ValvePak/ValvePak/ValvePak/ValvePak/Package.cs:line 157
   at GUI.Types.Viewers.Package.Create(VrfGuiContext vrfGuiContext, Byte[] input) in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Types\Viewers\Package.cs:line 35
   at GUI.MainForm.ProcessFile(VrfGuiContext vrfGuiContext, PackageEntry file) in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\MainForm.cs:line 538
   at GUI.MainForm.<>c__DisplayClass22_0.<OpenFile>b__0() in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\MainForm.cs:line 456
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
[the vpk file.zip](https://github.com/SteamDatabase/ValveResourceFormat/files/10453864/the.vpk.file.zip)

### What version of VRF are you using? On what platform?

the latest one，Windows

**Comment by xPaw** [comment]
Where did this vpk come from and how was it created? Even vpk.exe in TF2 does not understand it.

**Comment by CENTURYWIND** [comment]
> Where did this vpk come from and how was it created? Even vpk.exe in TF2 does not understand it.
> 
> The version in this file is `01 FF FF FF` instead of `01 00 00 00` (replacing it manually in hex editor opens in the file VRF). So my question is how that happened, and how L4D2 reads it (I have a suspicion that it simply ignores the version).

Thanks for your reply！I modified it as you said, and successfully read the file.

This file is from [here](https://steamcommunity.com/sharedfiles/filedetails/?id=2816249873). I wanted to unpack and decompile the model to replace different characters, but it could not be read. As for how to cause it, to be honest, I don't know. This thing need to ask the original author.
To be honest, I don't understand VPK files very much. I just unpack and package some simple mods.Maybe as you said, the game simply ignores the file version.

**Comment by xPaw** [comment]
I'd rather not put a hack in to support this before understanding how this happened. If you can figure out how this vpk was created that would be good.

Just for sanity check, can you try changing first 01 to 02 (and then anything else), and see if L4D2 can still load it?

**Comment by CENTURYWIND** [comment]
> I'd rather not put a hack in to support this before understanding how this happened. If you can figure out how this vpk was created that would be good.
> 
> Just for sanity check, can you try changing first 01 to 02 (and then anything else), and see if L4D2 can still load it?

In fact, I don't really understand, but it's enough for me to be able to read this file
I tried to change first 01 in  01 FF FF FF  to 02. L4D2 can still be read and run well, and VRF still can't read it：Bad VPK Version (4294967042) （not xxxxx7041）

**Comment by CENTURYWIND** [comment]
Of course, if there is anything I can do, I can help.
(It may be difficult to contact the original author)

**Comment by xPaw** [comment]
> L4D2 can still be read and run well

That's what I wanted to know, which leads me to believe the game just ignores the version altogether.

**Comment by CENTURYWIND** [comment]
> 
Indeed, the method to fix this is very simple. There is no need to add special support. I understand.

I have  asked the author on the Steam Workshop page, but since the two authors have not replied to any comment, I think the hope of getting a reply is very slim.
I will let you know as soon as there is a reply.

**Comment by CENTURYWIND** [comment]
> I do want to know what software created this vpk though, either it's a bug there or they intentionally try to do a silly "DRM" for third party software.

Well, the author replied to me, saying that it was just a "use less little encryption"It seems that he doesn't want to reveal how it was made. I guess he may have modified the file directly with the hexadecimal editor

**Comment by xPaw** [comment]
Yeah that's just silly. I'm gonna close this as I don't want to allow arbitrary versions. Consumers of this library can fix the version up in the file if they really want to.
