### ISSUE TITLE
Findings based on disassembly

### ISSUE THREAD

**Issue by BenLubar** [SteamDatabase/ValvePak#5]
- The metadata that can be included after directory entries is *never* used as part of the file when reading it.
- There are two special archive IDs: 0x7fff (current archive, for non-_dir archives), and 0xffff (which means "end of list")
- Each VPK entry has one *or more* archive locations, terminated by 0xffff (which does not have an offset or size after it)
- Archive locations are concatenated to create the file's actual content while reading

**Comment by xPaw** [comment]
Findings for what?

**Comment by BenLubar** [comment]
How VPK works in the packfile library that Source Engine uses to read them.

**Comment by xPaw** [comment]
This library already works with source engine vpks fine.

What is this issue for?

**Comment by BenLubar** [comment]
Currently, with this library, [the metadata is concatenated with the file's contents](https://github.com/SteamDatabase/ValvePak/blob/master/ValvePak/ValvePak/Package.cs#L329-L334) and [files that use more than one archive location are considered malformed](https://github.com/SteamDatabase/ValvePak/blob/master/ValvePak/ValvePak/Package.cs#L438-L443).

As far as I know, no Valve title uses the metadata field, but it might be worth changing the behavior in this library for correctness.

**Comment by xPaw** [comment]
> Currently, with this library, [the metadata is concatenated with the file's contents](https://github.com/SteamDatabase/ValvePak/blob/master/ValvePak/ValvePak/Package.cs#L329-L334)

As far as I can tell this is correct behaviour. It's basically a "preload".

https://github.com/perilouswithadollarsign/cstrike15_src/blob/f82112a2388b841d72cb62ca48ab1846dfcc11c8/vpklib/packedstore.cpp#L1190-L1203

> [files that use more than one archive location are considered malformed](https://github.com/SteamDatabase/ValvePak/blob/master/ValvePak/ValvePak/Package.cs#L438-L443).

Where are you getting this from?

If you think there are bugs, the best way to report them is to have a vpk that can reproduce them.

**Comment by BenLubar** [comment]
Hmm, I must have done something wrong in my analysis.

**Comment by xPaw** [comment]
Perhaps you saw the `CFilePartDescr m_PartDescriptors[1];                    // variable length` stuff, but they only ever use part 0 from what I can tell.
